export type DealFormErrors = {
  name?: string[],
  account?: string[],
  assigned_to?: string[],
  account_name?: string[],
  phone?: string[],
  email?: string[],
  value?: string[],
  lead_attachment?: string[],
  opportunity_amount?: string[],
  website?: string[],
  description?: string[],
  contacts?: string[],
  stage?: string[],
  deal_source?: string[],
  industry?: string[],
  currency?: string[],
  country?: string[],
  close_date?: string[],
  probability?: number[],
  file?: string[],
};